pipeline {
    agent any
    
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    
    stages {
        stage ('Git init') {
            steps {
                echo 'Git Init'
                git url:'https://github.com/superstarseonhoon/spring-petclinic.git/',
                branch: 'main', credentialsId: 'gitCredentials'
            }
        }
        stage('Build') {
            steps {
                echo 'Build'
                sh 'mvn -Dmaven.test.failure.ignore=ture clean package'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }  
    }
}
